create table public."SurveyResults" (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  survey_schema_id bigint null,
  survey_results json null,
  constraint SurveyResults_pkey primary key (id),
  constraint SurveyResults_survey_schema_id_fkey foreign KEY (survey_schema_id) references "SurveySchemas" (id) on update CASCADE on delete set null
) TABLESPACE pg_default;

create table public."SurveySchemas" (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  content json null,
  constraint SurveySchemas_pkey primary key (id)
) TABLESPACE pg_default;